namespace ProjectEuler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    ///
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///
    /// Find the sum of all the even-valued terms in the sequence which do not exceed four million.
    /// </summary>
    [Result(Name = "sum", Expected = "4613732")]
    public class Problem002 : Problem
    {
        public override string Solve(string resource)
        {
            long nm1 = 1;
            long nm2 = 0;

            long sum = 0;

            while (true)
            {
                long n = nm1 + nm2;

                if (n >= 4000000)
                {
                    break;
                }

                if (n % 2 == 0)
                {
                    sum += n;
                }

                nm2 = nm1;
                nm1 = n;
            }

            return sum.ToString();
        }
    }
}
